baseURL = "https://ztmeow.com/"
languageCode = "en-us"
title = "主题喵"
copyright = "© 2020 主题喵 <a href='http://beian.miit.gov.cn' target='blank'>桂ICP备15007841号-2</a>"
theme = "hugo-notepadium"
publishDir = "docs"